apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: sparkimagesglebs.azurecr.io/spark-py:3.0.0
        name: nginx
        imagePullPolicy: Always
        args: ["/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: sparkspcidsecret
              key: clientid
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:
              name: secrets-store-creds
