apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
  labels:
    usage: spark-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: sparkfiles
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: spark-pv
