apiVersion: v1
kind: Pod
spec:
  containers:
  - volumeMounts:
    - name: azure-secrets
      mountPath: /mnt/azure-secrets
      readOnly: true
    env:
      - name: CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: akvsecrets
            key: clientid
      - name: CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: akvsecrets
            key: clientsecret
      - name: STORAGE_AK
        valueFrom:
          secretKeyRef:
            name: akvsecrets
            key: storageak
      - name: SPARK_CONF_DIR
        value: "/mnt/azure/spark_conf"
  volumes:
  - name: azure-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-sparksecretskv-user-msi"