apiVersion: v1
kind: Pod
metadata:
  name: spark-submit-pod-adls-demo-2
  labels:
    purpose: demonstrate-command
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: spark-submit-test-deploy-container-v2
    image: sparkimagesglebs.azurecr.io/spark-py:3.0.0
    imagePullPolicy: Always
    args: ["/opt/spark/bin/spark-submit", "--master", "k8s://https://sparkakscluster-dns-46f9cb01.hcp.westeurope.azmk8s.io:443", "--deploy-mode", "cluster", "--name", "spark-app-adls-demo-2", "--conf", "spark.executor.instances=1", "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark", "--conf", "spark.kubernetes.container.image=sparkimagesglebs.azurecr.io/spark-py:3.0.0", "--conf", "spark.kubernetes.container.image.pullPolicy=Always", "--conf", "spark.driver.extraClassPath=/mnt/azure/jars/wildfly-openssl-1.0.7.Final.jar:/mnt/azure/jars/hadoop-azure-3.2.1.jar:/mnt/azure/jars/azure-storage-7.0.0.jar", "--conf", "'spark.driver.extraJavaOptions=-Dorg.wildfly.openssl.path=/mnt/azure/jars'", "--conf", "'spark.executor.extraJavaOptions=-Dorg.wildfly.openssl.path=/mnt/azure/jars'", "--jars", "local:///mnt/azure/jars/hadoop-azure-3.2.1.jar,local:///mnt/azure/jars/wildfly-openssl-1.0.7.Final.jar,local:///mnt/azure/jars/azure-storage-7.0.0.jar", "--conf", "spark.kubernetes.driver.volumes.persistentVolumeClaim.azure.mount.path=/mnt/azure", "--conf", "spark.kubernetes.driver.volumes.persistentVolumeClaim.azure.options.claimName=spark-pvc", "--conf", "spark.kubernetes.executor.volumes.persistentVolumeClaim.azure.mount.path=/mnt/azure", "--conf", "spark.kubernetes.executor.volumes.persistentVolumeClaim.azure.options.claimName=spark-pvc", "--conf", "spark.kubernetes.driver.podTemplateFile=/mnt/azure/spark_templates/csi_template_envs.yaml", "local:///mnt/azure/pyjobs/test_adls_wout_creds.py"]
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
  serviceAccountName: spark
  restartPolicy: Never
  volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: spark-pvc
