apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: test-template
spec:
  containers:
    - name: template-container
      volumeMounts:
        - name: azure-secrets
          mountPath: /mnt/azure-secrets
          readOnly: true
  volumes:
  - name: azure-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-sparksecretskv-user-msi"