apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: test-template
spec:
  containers:
    - name: template-container
      volumeMounts:
        - name: azure
          mountPath: /mnt/azurever2
  volumes:
  - name: azurev
    persistentVolumeClaim:
      claimName: spark-pvc